<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Library</OutputType>
    <RootNamespace>NeuroSDR.Web</RootNamespace>
    <AssemblyName>NeuroSDR.Web</AssemblyName>
    <DefaultItemExcludes>$(DefaultItemExcludes);_icongen\**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <Content Update="wwwroot\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

</Project>
